import { Inter } from "next/font/google";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";
import Navbar from "@/components/Navbar";
import Topbar from "@/components/Topbar";
import { Toaster } from "@/components/ui/sonner";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await auth();
  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body className={`${inter.className} h-screen max-w-full`}>
          <NextTopLoader />
          <Topbar />
          <Navbar />
          <main className="h-full mt-12 mb-12 md:mb-0 md:ml-12">
            {children}
          </main>
          <Toaster
            position="top-center"
            closeButton
            toastOptions={{
              // unstyled: true,
              classNames: {
                toast: "dark:bg-black bg-white",
                // title: 'text-red-400',
                // description: 'text-red-400',
                // actionButton: 'bg-zinc-400',
                // cancelButton: 'bg-orange-400',
                // closeButton: 'bg-lime-400',
              },
            }}
          />
        </body>
      </SessionProvider>
    </html>
  );
}
